import Head from 'next/head'
import { gql } from "@apollo/client";
import client from "../apollo-client";


export default function Test() {
  const getItems = async function(){
    const data = await client.query({
      query: gql`
      query ExampleQuery {
        countries {
          code
          name
        }
      }
     ` 
    });
console.log(data.data.countries);   
  }
  getItems();
  return (
    <div className="">
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1>Test1AA</h1>
      </div>
    </div>
  )
}
